services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - ir-network

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    command:
      - run
      - /etc/alloy/config.alloy
    volumes:
      - ../monitoring/alloy/config.alloy:/etc/alloy/config.alloy
      - ../logs:/logs
    ports:
      - "12345:12345"
      - "4317:4317"
      - "4318:4318"
    env_file:
      - ../.env.local
    depends_on:
      - loki          # tempo removed
    networks:
      - ir-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3002:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - loki          # prometheus + tempo removed
    networks:
      - ir-network

volumes:
  grafana-storage:

networks:
  ir-network: